"""add restaurant price range

Revision ID: acab4b9280da
Revises: 87a245b1d622
Create Date: 2026-08-08 11:17:29.048836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acab4b9280da'
down_revision: Union[str, Sequence[str], None] = '87a245b1d622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('price_range', sa.String(length=10), nullable=False ,  server_default="$$"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'price_range')
    # ### end Alembic commands ###
